steps:
  - name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['test']

  - name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['package']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/treinamentociandt/fake-cliente:latest', '-t', 'gcr.io/treinamentociandt/fake-cliente:$SHORT_SHA', '.']