steps:
  - id: 'Testes'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['test']

  - id: 'Build'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['package']

  - id: 'Create image'
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/treinamentociandt/fake-cliente:latest', '-t', 'gcr.io/treinamentociandt/fake-cliente:$SHORT_SHA', '.']

  - id: 'Run image'
    name: gcr.io/cloud-builders/docker
    args: ['run', '-d', '--name', 'myapp', 'gcr.io/treinamentociandt/fake-cliente:latest']