steps:
  - name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['test']

  - name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['package']

  - name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate','-Dexpression=project.name','-q','-DforceStdout>target/IMAGE']

  - name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate','-Dexpression=project.version','-q','-DforceStdout>target/VERSION']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/treinamentociandt/fake-cliente:latest', '-t', 'gcr.io/treinamentociandt/fake-cliente:${_NODE_VERSION_1}', '.']

  substitutions:
    _NODE_VERSION_1: $(cat target/VERSION)