steps:
  - id: 'Testes'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['test']

  - id: 'Build'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['package']

  - id: 'Criar image'
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/treinamentociandt/fake-cliente:latest', '-t', 'gcr.io/treinamentociandt/fake-cliente:$SHORT_SHA', '.']

  - id: 'Publicar imagem LATEST'
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/treinamentociandt/fake-cliente:latest']

  - id: 'Publicar imagem ESPECIFICA'
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/treinamentociandt/fake-cliente:$SHORT_SHA']

  - id: 'Deploy'
    name: gcr.io/cloud-builders/gcloud
    args: ['run', 'deploy', 'myapp-cloudrun', '--image', 'gcr.io/treinamentociandt/fake-cliente:latest', '--regions', 'us-central', 'platform', 'managed', '--allow-unauthenticated']