steps:
  - id: 'Geracao de pacote'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['package', '-DskipTests']

  - id: 'Testes'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['test']

  - id: 'Geração de imagem'
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/treinamentofinal/fake-clientes:latest', '-t', 'gcr.io/treinamentofinal/fake-clientes:$SHORT_SHA', '.']

  - id: 'Publicar imagem LATEST'
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/treinamentofinal/fake-clientes:latest']

  - id: 'Publicar imagem HISTORICO'
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/treinamentofinal/fake-clientes:$SHORT_SHA']