steps:
  - id: 'Deploy'
    name: gcr.io/cloud-builders/gcloud
    args: [ 'run','deploy','aplicacao-fake-clientes','--image','gcr.io/treinamentocit2/fake-clientes:latest','--region','us-central1','--platform','managed','--allow-unauthenticated',]