steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: [ 'test' ]

#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/treinamentociandt/fake-cliente:latest', '-t', 'gcr.io/treinamentociandt/fake-cliente:$SHORT_SHA', '.']