steps:
  - id: 'Geração de pacote'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['package']

  - id: 'Execução de testes'
    name: maven:3.8.3-openjdk-11
    entrypoint: mvn
    args: ['test']